apiVersion: apps/v1
kind: Deployment
metadata:
  name: credbull-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credbull-user
  template:
    metadata:
      labels:
        app: credbull-user
    spec:
      containers:
        - name: credbull-user-container
          image: credbull-user-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: credbull-env
          env:
             - name: REDIS_HOST
               value: redis
             - name: REDIS_PORT
               value: "6379"


---
apiVersion: v1
kind: Service
metadata:
  name: credbull-user-service
spec:
  selector:
    app: credbull-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
